### Parameters needed to be updated or provided on the CLI with
### --config KEY=VALUE
# Path to the sample sheet CSV containing metadata. You must use an absolute
# path if you are using --directory
sample_sheet: "data/samplesheet.csv"
# Path to the CSV file containing the comparisons to do. You must use an absolute
# path if you are using --directory
comparison_sheet: "data/comparison.csv"
# This should be GRCm39 or GRCh38
selected_genome: "GRCm39"

### Parameters to update if you are not running the pipeline from the 
### repository or if you are using --directory.
# You must use an absolute path if you are using --directory
atria_image: "atria/atria-4.1.1.sif"

### Parameters dependant on your machine/HPC
# Number of threads to use for parallel processes
threads: 20
star_ram_limit: 40000000000

### Parameters to skip section of the pipeline
# If your reads need trimming, use true, otherwise, false
trim_reads: true
# If you don't want to compare sample, use false
do_comparison: true

### Parameters to update if you already have the files and you don't want
### to download the files again
genome_fasta: "resources/{selected_genome}_genome.fa"
genes_gtf: "resources/{selected_genome}_annotation.gtf"
cdna_fasta: "resources/{selected_genome}_transcriptome.fa"
star_index: "resources/star_index_{selected_genome}"
salmon_index: "resources/salmon_index_{selected_genome}"

### These probably don't need updating
GRCm39:
  species_name: "mus_musculus"
  species_name_upper: "Mus_musculus"
  release_version: 113
GRCh38:
  species_name: "homo_sapiens"
  species_name_upper: "Homo_sapiens"
  release_version: 113

go_enrichment_pvalue: 0.05
salmon_libtype: "A"
salmon_extra_args: ""