# Path to the sample sheet CSV containing metadata
sample_sheet: "data/samplesheet_full.csv"   # Path to your samplesheet

# Column names in the sample sheet for metadata
group_column: "group"                # Column for group information
replicate_column: "replicate"        # Column for replicate information
fastq_1_column: "fastq_1"            # Column for first FASTQ file URL
fastq_2_column: "fastq_2"            # Column for second FASTQ file URL
strandedness_column: "strandedness"  # Column for strandedness information
   # Directory where quality control results will be stored
# Number of threads to use for parallel processes
threads: 20

# Genome reference data for different organisms
genome:
  hg38:
    genome_fa: "../results/genome/human/hg38_genome.fa"
    gtf: "../results/genome/human/hg38_annotation.gtf"
    transcriptome: "../results/genome/human/hg38_transcriptome.fa"
    star_index: "../results/genome/human/star_index"
    salmon_index: "../results/genome/human/salmon_index"
  mm39:
    genome_fa: "../results/genome/mouse/mm39_genome.fa"
    gtf: "../results/genome/mouse/mm39_annotation.gtf"
    transcriptome: "../results/genome/mouse/mm39_transcriptome.fa"
    star_index: "../results/genome/mouse/star_index_genome"
    salmon_index: "../results/genome/mouse/salmon_index_genome"

